[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"


[project]
name = "cmd"
version = "0.1.0"
description = "Python Frontend"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
  "numpy==2.4",
  "maturin==1.12.4",
  "librosa",
  "pydub"
]
